# Generated by Django 5.1.1 on 2024-09-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_pack_price_pack_download_url_alter_pack_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
