# Generated by Django 5.1.1 on 2024-09-18 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
