# Generated by Django 5.1.1 on 2024-09-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_customuser_promo_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
