# Generated by Django 5.1.1 on 2024-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='users', to='main_app.coupon'),
        ),
    ]
